# pyproject.toml (dependencies section)
[project]
name = "llm-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.0",
    "google-genai>=1.43.0",
    "pygithub>=2.8.1",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.37.0",
]
